// Package cost tracks token usage and dollar cost across an agent
// session. The Tracker is fed Usage data from each LLM call and
// computes incremental + cumulative cost using per-provider Pricing.
//
// The Tracker is immutable — every update returns a new Tracker rather
// than mutating in place. This follows the project's "no mutation"
// rule: state changes flow through the call graph as values, never as
// shared references. The Tracker is ~40 bytes; copying is effectively
// free on the hot path.
//
// Deferred (will land with later features):
//   - ToMetadata / RestoreFromMetadata — session persistence
//   - JSON unmarshal helpers — adapters build Usage from typed
//     provider.Usage; no JSON parser needed here.
//   - structured logging via log/slog — added when logging lands globally.
package cost

import "fmt"

// TokenUsage is the token accounting from a single LLM call, parsed
// from the provider's `usage` field. CacheRead and CacheCreate are
// provider-specific (Anthropic prompt caching today, OpenAI auto-caching
// later) — they're zero when the provider doesn't report them.
type TokenUsage struct {
	// PromptTokens — input tokens this call (INCLUDING cached tokens).
	PromptTokens int64

	// CompletionTokens — output tokens generated by the model.
	CompletionTokens int64

	// CacheReadTokens — subset of PromptTokens served from the cache.
	// Billed at cacheReadDiscount (10%) of normal input price.
	CacheReadTokens int64

	// CacheCreateTokens — tokens written to the provider's cache this
	// call. Not currently billed in our computation (most providers
	// charge at the regular input rate for cache writes); kept as a
	// field for future per-provider rules.
	CacheCreateTokens int64
}

// Pricing carries per-million-token prices for a model. Zero Pricing
// (both fields 0) is the "no pricing info" sentinel — RecordUsage
// still advances token counts but returns 0 for incremental cost.
type Pricing struct {
	// InputPricePerMillion — USD per 1,000,000 input tokens.
	InputPricePerMillion float64

	// OutputPricePerMillion — USD per 1,000,000 output tokens.
	OutputPricePerMillion float64
}

// Tracker is the immutable session-level cost accumulator. The zero
// value is a valid empty tracker (no constructor needed). All update
// methods return a new Tracker; callers must reassign.
type Tracker struct {
	// TotalInputTokens — sum of PromptTokens across all calls.
	TotalInputTokens int64

	// TotalOutputTokens — sum of CompletionTokens across all calls.
	TotalOutputTokens int64

	// TotalCostUSD — sum of incremental costs across all calls.
	TotalCostUSD float64

	// CallCount — number of recorded LLM calls this session.
	CallCount int64

	// BudgetUSD — optional spending cap. 0 means "no budget set";
	// IsOverBudget returns false in that case. Set directly via
	// struct literal: Tracker{BudgetUSD: 5.0}.
	BudgetUSD float64
}

const (
	// over200KThreshold — Anthropic charges higher rates for the
	// portion of an input prompt that exceeds 200K tokens.
	over200KThreshold = 200_000

	// over200KMultiplier — multiplier applied to InputPricePerMillion
	// for tokens past over200KThreshold.
	over200KMultiplier = 1.5

	// cacheReadDiscount — cache-read tokens billed at this fraction
	// of the normal input price (10%).
	cacheReadDiscount = 0.1
)

// RecordUsage returns a new Tracker reflecting the usage applied, plus
// the incremental cost in USD for this call. The original Tracker is
// untouched (immutable). A zero Pricing yields a 0 incremental cost
// while still advancing token totals.
func (t Tracker) RecordUsage(usage TokenUsage, pricing Pricing) (Tracker, float64) {
	incrementalCost := computeCost(usage, pricing)
	return Tracker{
		TotalInputTokens:  t.TotalInputTokens + usage.PromptTokens,
		TotalOutputTokens: t.TotalOutputTokens + usage.CompletionTokens,
		TotalCostUSD:      t.TotalCostUSD + incrementalCost,
		CallCount:         t.CallCount + 1,
		BudgetUSD:         t.BudgetUSD,
	}, incrementalCost
}

// IsOverBudget reports whether the session has reached or exceeded its
// configured budget. Returns false when no budget is set (BudgetUSD <= 0).
func (t Tracker) IsOverBudget() bool {
	return t.BudgetUSD > 0 && t.TotalCostUSD >= t.BudgetUSD
}

// RemainingBudget returns the USD amount still available before the
// budget is exhausted, clamped to 0. Returns 0 when no budget is set.
func (t Tracker) RemainingBudget() float64 {
	if t.BudgetUSD <= 0 {
		return 0
	}
	return max(0, t.BudgetUSD-t.TotalCostUSD)
}

// FormatCost renders the total cost for display. Uses 4 decimal places
// for sub-penny amounts so cost is visible early in a session
// ("$0.0042"); switches to 2 decimals once the total reaches a cent
// ("$1.23").
func (t Tracker) FormatCost() string {
	if t.TotalCostUSD < 0.01 {
		return fmt.Sprintf("$%.4f", t.TotalCostUSD)
	}
	return fmt.Sprintf("$%.2f", t.TotalCostUSD)
}

// computeCost is the pure-function cost formula. Factors out three
// components: tiered input cost (with 200K surcharge), cache-read cost
// at the discount rate, and output cost. Returns 0 for zero Pricing.
func computeCost(usage TokenUsage, pricing Pricing) float64 {
	var inputCost float64

	if usage.PromptTokens > over200KThreshold {
		base := float64(over200KThreshold) / 1_000_000 * pricing.InputPricePerMillion
		over := float64(usage.PromptTokens-over200KThreshold) / 1_000_000 *
			pricing.InputPricePerMillion * over200KMultiplier
		inputCost = base + over
	} else {
		inputCost = float64(usage.PromptTokens) / 1_000_000 * pricing.InputPricePerMillion
	}

	cacheCost := float64(usage.CacheReadTokens) / 1_000_000 *
		pricing.InputPricePerMillion * cacheReadDiscount

	outputCost := float64(usage.CompletionTokens) / 1_000_000 * pricing.OutputPricePerMillion

	return inputCost + cacheCost + outputCost
}
